[project]
name = "python-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.135.3",
    "jupyter>=1.1.1",
    "langchain>=1.2.15",
    "langchain-community>=0.4.1",
    "langchain-deepseek>=1.0.1",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.1.13",
    "lxml>=6.1.0",
    "markdown>=3.10.2",
    "pandas>=3.0.1",
    "pyjwt>=2.12.1",
    "python-multipart>=0.0.26",
    "redis>=7.4.0",
    "sentence-transformers>=5.4.1",
    "tortoise-orm>=1.1.7",
    "unstructured>=0.22.22",
    "uvicorn>=0.44.0",
]
